# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Build documentation in the docs/ directory with Sphinx
# Uncomment if using Sphinx instead of MkDocs
# sphinx:
#   configuration: docs/conf.py

# Build settings
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Python dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Optionally build PDF and ePub formats
formats:
  - pdf
  - epub
